from tasks.task_20 import BastShoe


def test_regression():
    assert BastShoe("1 Привет") == "Привет"
    assert BastShoe("1 , Мир!") == "Привет, Мир!"
    assert BastShoe("1 ++") == "Привет, Мир!++"
    assert BastShoe("2 2") == "Привет, Мир!"
    assert BastShoe("4") == "Привет, Мир!++"
    assert BastShoe("4") == "Привет, Мир!"
    assert BastShoe("1 *") == "Привет, Мир!*"
    assert BastShoe("4") == "Привет, Мир!"
    assert BastShoe("4") == "Привет, Мир!"
    assert BastShoe("4") == "Привет, Мир!"
    assert BastShoe("3 6") == ","
    assert BastShoe("2 100") == ""
    assert BastShoe("1 Привет") == "Привет"
    assert BastShoe("1 , Мир!") == "Привет, Мир!"
    assert BastShoe("1 ++") == "Привет, Мир!++"
    assert BastShoe("4") == "Привет, Мир!"
    assert BastShoe("4") == "Привет"
    assert BastShoe("5") == "Привет, Мир!"
    assert BastShoe("4") == "Привет"
    assert BastShoe("5") == "Привет, Мир!"
    assert BastShoe("5") == "Привет, Мир!++"
    assert BastShoe("5") == "Привет, Мир!++"
    assert BastShoe("5") == "Привет, Мир!++"
    assert BastShoe("4") == "Привет, Мир!"
    assert BastShoe("4") == "Привет"
    assert BastShoe("2 2") == "Прив"
    assert BastShoe("4") == "Привет"
    assert BastShoe("5") == "Прив"
    assert BastShoe("5") == "Прив"
    assert BastShoe("5") == "Прив"
